image: gitlab/dind
services:
  - docker:dind

stages:
  - build
  - release
  - prod
  - cleanup

variables:
  DOCKER_REPOSITORY: $CI_REGISTRY_IMAGE:latest
  APPLICATION_NAME: quickt
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DATABASE_USER: $DATABASE_USER
  DATABASE_PASSWORD: $DATABASE_PASSWORD
  DATABASE_DB: $DATABASE_DB
  DATABASE_PORT: $DATABASE_PORT
  DATABASE_HOST: $DATABASE_HOST
  DATABASE_CONNECTION_TIMEOUT_MS: 5000
  DATABASE_QUERY_TIMEOUT_MS: 10000
  DATABASE_IDLE_TIMEOUT_MS: 0
  HOST: $HOST
  TRAEFIK_HOST: $TRAEFIK_HOST

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
    - tools
  script:
    - docker build -t $CONTAINER_TEST_IMAGE -f Dockerfile .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  tags:
    - tools
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

prod:
  stage: prod
  tags:
    - tools
  script:
    - docker-compose -f docker-compose.prod.yml up --force-recreate -d
  only:
    - main
  environment:
    name: production
    url: https://demo.quickt.de

cleanup:
  stage: cleanup
  tags:
    - tools
  script:
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker rmi $(docker images -f "dangling=true" -q) --force
