version: '2'

services:
  quickt-client:
    image: ${DOCKER_REPOSITORY}
    container_name: "quickt_client"
    labels:
      traefik.http.routers.quickt-http.rule: "Host(`quickt.de`)"
      traefik.http.routers.quickt-http.entrypoints: "web"
      traefik.http.routers.quickt-http.middlewares: "redirect-to-https"
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"

      traefik.http.routers.quickt-https.rule: "Host(`quickt.de`)"
      traefik.http.routers.quickt-https.entrypoints: "websecure"
      traefik.http.routers.quickt-https.tls.certresolver: "letsencrypt"
    working_dir: /app/client
    user: node
    environment:
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - default
    restart: unless-stopped
    command: sh -c "ls -la && npm start"

  quickt-server:
    image: ${DOCKER_REPOSITORY}
    container_name: "quickt_server"
    labels:
      traefik.enable: "false"
    working_dir: /app/server
    user: node
    environment:
      DW_DATABASE_DB: ${DW_DATABASE_DB}
      DW_DATABASE_PORT: ${DW_DATABASE_PORT}
      DW_DATABASE_USER: ${DW_DATABASE_USER}
      DW_DATABASE_HOST: ${DW_DATABASE_HOST}
      DW_DATABASE_PASSWORD: ${DW_DATABASE_PASSWORD}
      DATABASE_CONNECTION_TIMEOUT_MS: 5000
      DATABASE_QUERY_TIMEOUT_MS: 10000
      DATABASE_IDLE_TIMEOUT_MS: 0
    networks:
      - default
    restart: unless-stopped
    command: sh -c "ls -la && npm start"

  quickt-database:
    image: "postgres:11"
    container_name: "quickt_database"
    labels:
      traefik.enable: "false"
    environment:
      POSTGRES_USER: ${DW_DATABASE_USER}
      POSTGRES_PASSWORD: ${DW_DATABASE_PASSWORD}
      POSTGRES_DB: ${DW_DATABASE_DB}
      PGPORT: 5433
    ports:
      - "${DW_DATABASE_PORT}:5433"
    volumes:
      - /data/postgres-data:/var/lib/postgresql/data/
    networks:
      - default

networks:
  default:
    external:
      name: reverse_proxy
