version: '2'

services:
  quickt-client:
    image: ${DOCKER_REPOSITORY}
    container_name: "${APPLICATION_NAME}_client"
    labels:
      traefik.http.routers.quickt.rule: "Host(\"${TRAEFIK_HOST}\")"
      traefik.http.routers.quickt.tls: "true"
      traefik.http.services.quickt.loadbalancer.server.port: "3001"
    working_dir: /app
    user: node
    networks:
      - default
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: sh -c "cd client && npm start"

  quickt-server:
    image: ${DOCKER_REPOSITORY}
    container_name: "${APPLICATION_NAME}_server"
    labels:
      traefik.enable: "false"
    working_dir: /app
    user: node
    ports:
      - "3001:3001"
    networks:
      - default
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: unless-stopped
    command: sh -c "cd server && npm run start:dev"

  quickt-database:
    image: "postgres:11"
    container_name: "${APPLICATION_NAME}_database"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "5433:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - default

networks:
  default:
    external:
      name: reverse_proxy

volumes:
  database-data: