version: '2'

services:
  dw-client:
    image: ${DOCKER_REPOSITORY}
    labels:
      traefik.http.routers.dw-translations.rule: "Host(`quickt.de`, `www.quickt.de`)"
      traefik.http.routers.dw-translations.entrypoints: "websecure"
      traefik.http.routers.dw-translations.tls.certresolver: "letsencrypt"
    working_dir: /app/client
    user: node
    networks:
      - reverse_proxy
    restart: unless-stopped
    command: sh -c "ls -la && npm start"
    ports:
      - "3000:3000"

  dw-server:
    image: ${DOCKER_REPOSITORY}
    labels:
      traefik.enable: "false"
    working_dir: /app/server
    user: node
    ports:
      - "3001:3001"
    networks:
      - reverse_proxy
    restart: unless-stopped
    command: sh -c "ls -la && npm start"

  dw-database:
    image: "postgres:11"
    labels:
      traefik.enable: "false"
    environment:
      POSTGRES_USER: ${DW_DATABASE_USER}
      POSTGRES_PASSWORD: ${DW_DATABASE_PASSWORD}
      POSTGRES_DB: ${DW_DATABASE_DB}
      PGPORT: 5433
    ports:
      - "${DW_DATABASE_PORT}:5433"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - reverse_proxy

networks:
  reverse_proxy:

volumes:
  database-data:
