version: '2'

services:
  quickt-client:
    image: ${DOCKER_REPOSITORY}
    container_name: "quickt_client"
    labels:
      traefik.http.routers.quickt.rule: "Host(`quickt.localhost`)"
      traefik.http.routers.quickt.tls: "true"
      traefik.http.services.quickt.loadbalancer.server.port: "3001"
    working_dir: /app
    user: node
    networks:
      - reverse_proxy
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: sh -c "cd client && npm start"

  quickt-server:
    image: ${DOCKER_REPOSITORY}
    container_name: "quickt_server"
    labels:
      traefik.enable: "false"
    working_dir: /app
    user: node
    ports:
      - "3001:3001"
    networks:
      - reverse_proxy
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: unless-stopped
    command: sh -c "cd server && npm run start:dev"

  quickt-database:
    image: "postgres:11"
    container_name: "quickt_database"
    labels:
      traefik.enable: "false"
    environment:
      POSTGRES_USER: ${DW_DATABASE_USER}
      POSTGRES_PASSWORD: ${DW_DATABASE_PASSWORD}
      POSTGRES_DB: ${DW_DATABASE_DB}
      PGPORT: 5433
    ports:
      - "${DW_DATABASE_PORT}:5433"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - reverse_proxy

networks:
  reverse_proxy:

volumes:
  database-data:
